In [1]:
!pip install pandas
!pip install numpy

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [2]:
import pandas as pd
import numpy as np

In [3]:
#Series concept
#it is a column in a table
# 1D array
s1 = pd.Series([23,45,65,12,34])
s1

0    23
1    45
2    65
3    12
4    34
dtype: int64

In [4]:
s1 = pd.Series([23,45,65,12,34],index = ['x','y','z','m','n'])
s1

x    23
y    45
z    65
m    12
n    34
dtype: int64

In [5]:
s1 = pd.Series([23,45,65,12,34],index = ["maths","science","social","telugu","english"],dtype = "float")
s1

maths      23.0
science    45.0
social     65.0
telugu     12.0
english    34.0
dtype: float64

In [6]:
#using dictionaries
s2 = pd.Series({1:"maths",2:"science",3:"social",4:"telugu"})
s2

1      maths
2    science
3     social
4     telugu
dtype: object

In [7]:
s3 = pd.Series({"fruit":"mango","thing":"pen","liquid":"Juice"})
s3

fruit     mango
thing       pen
liquid    Juice
dtype: object

In [8]:
# by using DataFrame
#2D Arrays(rows and columns)
d1 = pd.DataFrame([12,13,14,15,16])
d1

    0
0  12
1  13
2  14
3  15
4  16

In [9]:
d2 = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])
d2

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [10]:
d3 = pd.DataFrame(s3)
d3

            0
fruit   mango
thing     pen
liquid  Juice

In [11]:

d4 = pd.DataFrame([[23,34,54],[45,43,34],[35,45,36]],index = ["kavya","deepu","yashu"],columns = ["maths",'english','telugu'])
d4

       maths  english  telugu
kavya     23       34      54
deepu     45       43      34
yashu     35       45      36

In [12]:
#creating DataFrom from list of dictionaries
#keys can be assigned to column names
dic = [{"kavya":1,"joe":2},{"alex":5,"dora":6},{"ema":2,"alice":4,"joe":1}]
pd.DataFrame(dic,index = [1,2,3])

   kavya  joe  alex  dora  ema  alice
1    1.0  2.0   NaN   NaN  NaN    NaN
2    NaN  NaN   5.0   6.0  NaN    NaN
3    NaN  1.0   NaN   NaN  2.0    4.0

In [13]:
#operations on DataFrame
d4

       maths  english  telugu
kavya     23       34      54
deepu     45       43      34
yashu     35       45      36

In [14]:
#accessing single column from the table
print(d4["maths"])

kavya    23
deepu    45
yashu    35
Name: maths, dtype: int64

In [15]:
print(d4["telugu"])

kavya    54
deepu    34
yashu    36
Name: telugu, dtype: int64

In [16]:
print(d4)

       maths  english  telugu
kavya     23       34      54
deepu     45       43      34
yashu     35       45      36

In [18]:
d4["total"] = d4["maths"] + d4["english"] + d4["telugu"]
d4

       maths  english  telugu  total
kavya     23       34      54    111
deepu     45       43      34    122
yashu     35       45      36    116

In [19]:
#pop operation (we can give column name for pop)
pop = d4.pop("total")
d4

       maths  english  telugu
kavya     23       34      54
deepu     45       43      34
yashu     35       45      36

In [20]:
del d4["english"]
d4

       maths  telugu
kavya     23      54
deepu     45      34
yashu     35      36

In [21]:
d4.insert(0,"hindi",[34,54,37])
d4

       hindi  maths  telugu
kavya     34     23      54
deepu     54     45      34
yashu     37     35      36

In [22]:
d = {"hindi":50,"telugu":45}
df = d4._append(d,ignore_index = True)
df

   hindi  maths  telugu
0     34   23.0      54
1     54   45.0      34
2     37   35.0      36
3     50    NaN      45

In [23]:
import numpy as np
d6 = pd.DataFrame({"abc":np.random.randint(3,7,size=(10)),"bcd":np.random.randint(2,8,size=(10)),"cde":np.random.randint(2,7,size=(10))})
d6

   abc  bcd  cde
0    6    6    3
1    3    3    4
2    4    6    4
3    6    7    4
4    4    5    4
5    3    5    3
6    6    4    5
7    4    4    3
8    3    2    3
9    5    3    2

In [24]:
d6.head()

   abc  bcd  cde
0    6    6    3
1    3    3    4
2    4    6    4
3    6    7    4
4    4    5    4

In [25]:
d6.tail()

   abc  bcd  cde
5    3    5    3
6    6    4    5
7    4    4    3
8    3    2    3
9    5    3    2

In [26]:
d6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   abc     10 non-null     int64
 1   bcd     10 non-null     int64
 2   cde     10 non-null     int64
dtypes: int64(3)
memory usage: 372.0 bytes

In [27]:
d6.info()
d6.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   abc     10 non-null     int64
 1   bcd     10 non-null     int64
 2   cde     10 non-null     int64
dtypes: int64(3)
memory usage: 372.0 bytes

             abc        bcd        cde
count  10.000000  10.000000  10.000000
mean    4.400000   4.500000   3.500000
std     1.264911   1.581139   0.849837
min     3.000000   2.000000   2.000000
25%     3.250000   3.250000   3.000000
50%     4.000000   4.500000   3.500000
75%     5.750000   5.750000   4.000000
max     6.000000   7.000000   5.000000

In [28]:
d6

   abc  bcd  cde
0    6    6    3
1    3    3    4
2    4    6    4
3    6    7    4
4    4    5    4
5    3    5    3
6    6    4    5
7    4    4    3
8    3    2    3
9    5    3    2

In [29]:
#lable based)we can give the row name and column name
#it give the value in that position
print(d6.loc[4,"abc"])
print(d6.loc[5,"cde"])

4
3

In [30]:
#slicing by using loc
d6.loc[4:8,["abc","cde"]]

   abc  cde
4    4    4
5    3    3
6    6    5
7    4    3
8    3    3

In [31]:
d6.loc[5:9,["abc","bcd","cde"]]

   abc  bcd  cde
5    3    5    3
6    6    4    5
7    4    4    3
8    3    2    3
9    5    3    2

In [32]:
d6.loc[[2,5,9],["abc","cde","bcd"]]

   abc  cde  bcd
2    4    4    6
5    3    3    5
9    5    2    3

In [33]:
#iloc (index based)
print(d6.iloc[3,2])
print(d6.iloc[4,1])

4
5

In [34]:
#iloc slicing [rows,colums] with specific
d6.iloc[2:6,[0,2]]

   abc  cde
2    4    4
3    6    4
4    4    4
5    3    3

In [35]:
#direct column access
d6.abc

0    6
1    3
2    4
3    6
4    4
5    3
6    6
7    4
8    3
9    5
Name: abc, dtype: int64

In [36]:
d6.cde

0    3
1    4
2    4
3    4
4    4
5    3
6    5
7    3
8    3
9    2
Name: cde, dtype: int64

In [37]:
#by using values attribute it converts data into 1D array
d6.bcd.values

array([6, 3, 6, 7, 5, 5, 4, 4, 2, 3])

In [38]:
d6["add"] = d6.abc.values + d6.bcd.values + d6.cde.values
d6

   abc  bcd  cde  add
0    6    6    3   15
1    3    3    4   10
2    4    6    4   14
3    6    7    4   17
4    4    5    4   13
5    3    5    3   11
6    6    4    5   15
7    4    4    3   11
8    3    2    3    8
9    5    3    2   10

In [39]:
x = [["kavya",101,20000],["deepu",102,25000],["radha",103,30000]]
df = pd.DataFrame(x,columns = ["name","id","salary"])
df

    name   id  salary
0  kavya  101   20000
1  deepu  102   25000
2  radha  103   30000

In [40]:
df[["id","salary"]]

    id  salary
0  101   20000
1  102   25000
2  103   30000

In [41]:
df._append({"name":"trisha","id":104,"salary":25000},ignore_index = True)

     name   id  salary
0   kavya  101   20000
1   deepu  102   25000
2   radha  103   30000
3  trisha  104   25000

In [42]:
s = pd.DataFrame(dic,index = [1,2,3])
s

   kavya  joe  alex  dora  ema  alice
1    1.0  2.0   NaN   NaN  NaN    NaN
2    NaN  NaN   5.0   6.0  NaN    NaN
3    NaN  1.0   NaN   NaN  2.0    4.0

In [43]:
s.isnull()

   kavya    joe   alex   dora    ema  alice
1  False  False   True   True   True   True
2   True   True  False  False   True   True
3   True  False   True   True  False  False

In [44]:
s.isnull().sum()

kavya    2
joe      1
alex     2
dora     2
ema      2
alice    2
dtype: int64

In [45]:
s.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, 1 to 3
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   kavya   1 non-null      float64
 1   joe     2 non-null      float64
 2   alex    1 non-null      float64
 3   dora    1 non-null      float64
 4   ema     1 non-null      float64
 5   alice   1 non-null      float64
dtypes: float64(6)
memory usage: 168.0 bytes

In [46]:
#temparirly delete the null value rows
s.dropna()

Empty DataFrame
Columns: [kavya, joe, alex, dora, ema, alice]
Index: []

In [47]:
s

   kavya  joe  alex  dora  ema  alice
1    1.0  2.0   NaN   NaN  NaN    NaN
2    NaN  NaN   5.0   6.0  NaN    NaN
3    NaN  1.0   NaN   NaN  2.0    4.0

In [48]:
s.fillna(value="None")

  kavya   joe  alex  dora   ema alice
1   1.0   2.0  None  None  None  None
2  None  None   5.0   6.0  None  None
3  None   1.0  None  None   2.0   4.0

In [58]:
import pandas as pd
df = pd.DataFrame({"Animals": ["Sparrow","Parrot","Parrot","Sparrow"], "Max speed" : [380,420,357,234],"Wind speed" : [380,420,357,234]})
df

   Animals  Max speed  Wind speed
0  Sparrow        380         380
1   Parrot        420         420
2   Parrot        357         357
3  Sparrow        234         234

In [59]:
df.groupby(["Animals"]).mean()

         Max speed  Wind speed
Animals
Parrot       388.5       388.5
Sparrow      307.0       307.0

In [63]:
# Kabaddi score
print("Kabaddi Score")
df1 = pd.DataFrame({"Department" : ["MCA","MBA","CSE","MCA","CSE","MBA"],"1st round" : [10,4,7,4,10,9],"2nd round" : [7,12,10,10,5,4]})
df1

Kabaddi Score

  Department  1st round  2nd round
0        MCA         10          7
1        MBA          4         12
2        CSE          7         10
3        MCA          4         10
4        CSE         10          5
5        MBA          9          4

In [69]:
df1.groupby(["Department"]).sum()

            1st round  2nd round
Department
CSE                17         15
MBA                13         16
MCA                14         17

In [70]:
df1.groupby(["Department"]).mean()

            1st round  2nd round
Department
CSE               8.5        7.5
MBA               6.5        8.0
MCA               7.0        8.5

In [71]:
#Transpose
df1.T

              0    1    2    3    4    5
Department  MCA  MBA  CSE  MCA  CSE  MBA
1st round    10    4    7    4   10    9
2nd round     7   12   10   10    5    4

In [75]:
#GetDummies
data = {"firstname" : ["Kavya","Lahari","Muni","Anitha","Mahitha"],
        "lastname" : ["Patil","Tavasi","Sharma","Devi","Ammuri"],
        "Department" : ["MCA","EEE","MBA","CSE","ECE"],
        "Country" : ["India","USA","UK","Germany","Australia"]}
details = pd.DataFrame(data,columns=["firstname","lastname","Department","Country"])
print(details)

  firstname lastname Department    Country
0     Kavya    Patil        MCA      India
1    Lahari   Tavasi        EEE        USA
2      Muni   Sharma        MBA         UK
3    Anitha     Devi        CSE    Germany
4   Mahitha   Ammuri        ECE  Australia

In [77]:
df1 = pd.get_dummies(details["Department"],dtype = "int")
df1

   CSE  ECE  EEE  MBA  MCA
0    0    0    0    0    1
1    0    0    1    0    0
2    0    0    0    1    0
3    1    0    0    0    0
4    0    1    0    0    0

In [79]:
df2 = pd.get_dummies(details["Country"],dtype = "int")
df2

   Australia  Germany  India  UK  USA
0          0        0      1   0    0
1          0        0      0   0    1
2          0        0      0   1    0
3          0        1      0   0    0
4          1        0      0   0    0

In [82]:
data1 = {"Studentname":["Kavya","Muni","Anitha","Deepu","Rohith"],
         "Department": ["MCA","MBA","EEE","ECE","CSE"],
         "Gender" : ["Female","Male","Female","Female","Male"],
         "State" : ["Andhra Pradesh","Telangana","Tamil Nadu","Karnataka","Maharashtra"]}
df3 = pd.DataFrame(data1,columns = ["Studentname","Department","Gender","State"])
df3

  Studentname Department  Gender           State
0       Kavya        MCA  Female  Andhra Pradesh
1        Muni        MBA    Male       Telangana
2      Anitha        EEE  Female      Tamil Nadu
3       Deepu        ECE  Female       Karnataka
4      Rohith        CSE    Male     Maharashtra

In [88]:
df4=pd.get_dummies(df3["Gender"],dtype = "int")
print(df4)
df5 = pd.get_dummies(df3["Department"],dtype = "int")
print(df5)
df6 = pd.get_dummies(df3["State"],dtype = "int")
print(df6)

   Female  Male
0       1     0
1       0     1
2       1     0
3       1     0
4       0     1
   CSE  ECE  EEE  MBA  MCA
0    0    0    0    0    1
1    0    0    0    1    0
2    0    0    1    0    0
3    0    1    0    0    0
4    1    0    0    0    0
   Andhra Pradesh  Karnataka  Maharashtra  Tamil Nadu  Telangana
0               1          0            0           0          0
1               0          0            0           0          1
2               0          0            0           1          0
3               0          1            0           0          0
4               0          0            1           0          0

In [103]:
india_weather =pd.DataFrame({"City" : ["Tirupati","Delhi","Maharashtra","Bangalore"],
                 "Temperature" : [34,45,35,30],
                 "Humidity" : [60,67,70,75]})

weather1 = pd.DataFrame(india_weather,columns=["City","Temperature","Humidity"])
print(weather1)

          City  Temperature  Humidity
0     Tirupati           34        60
1        Delhi           45        67
2  Maharashtra           35        70
3    Bangalore           30        75

In [104]:
US_weather = pd.DataFrame({"City":["New York","Chicago","Orlando"],
              "Temperature":[21,14,35],
              "Humidity":[68,63,78]
              })
weather2 = pd.DataFrame(US_weather,columns = ["City","Temperature","Humidity"])
weather2

       City  Temperature  Humidity
0  New York           21        68
1   Chicago           14        63
2   Orlando           35        78

In [105]:
df = pd.concat([india_weather,US_weather])
df

          City  Temperature  Humidity
0     Tirupati           34        60
1        Delhi           45        67
2  Maharashtra           35        70
3    Bangalore           30        75
0     New York           21        68
1      Chicago           14        63
2      Orlando           35        78

In [107]:
df = pd.concat([india_weather,US_weather],ignore_index = True)
df

          City  Temperature  Humidity
0     Tirupati           34        60
1        Delhi           45        67
2  Maharashtra           35        70
3    Bangalore           30        75
4     New York           21        68
5      Chicago           14        63
6      Orlando           35        78

In [113]:
#remove duplicates from the data by using drop_duplicates
import pandas as pd
info = pd.DataFrame({"Name":["John","Benny","Allice","Smith","Benny"],
                     "Age":[25,26,35,29,26]})
print(info)
print("*"*25)
info = info.drop_duplicates()
print(info)

     Name  Age
0    John   25
1   Benny   26
2  Allice   35
3   Smith   29
4   Benny   26
*************************
     Name  Age
0    John   25
1   Benny   26
2  Allice   35
3   Smith   29

In [118]:
employee = pd.DataFrame({"ID":[101,102,105,107,102,103,101],
                         "Department":["IT","HR","Finance","HR","HR","Finance","IT"],
                         "Salary":[40000,50000,45000,60000,50000,57000,40000]
                         })
print(employee)
print("-"*30)
remove_duplicates = employee.drop_duplicates()
print(remove_duplicates)

    ID Department  Salary
0  101         IT   40000
1  102         HR   50000
2  105    Finance   45000
3  107         HR   60000
4  102         HR   50000
5  103    Finance   57000
6  101         IT   40000
------------------------------
    ID Department  Salary
0  101         IT   40000
1  102         HR   50000
2  105    Finance   45000
3  107         HR   60000
5  103    Finance   57000

In [124]:
# apply() function in side function
def total_sal(salary):
  increment = 1000
  return salary+increment
data = pd.DataFrame({
    "dept1_salary" : [25000,30000,45000],
    "dept2_salary" : [30000,27000,50000]
})
print(data)
print("="*30)
print("After Salary increment")
df = data.apply(total_sal)
print(df)

   dept1_salary  dept2_salary
0         25000         30000
1         30000         27000
2         45000         50000
==============================
After Salary increment
   dept1_salary  dept2_salary
0         26000         31000
1         31000         28000
2         46000         51000

In [129]:
def total_marks(marks):
  assignment_marks = 10
  return marks + assignment_marks
data = pd.DataFrame({"section_A":[25,30,27,29,26],
                     "section_B":[30,21,26,29,27]})
print(data)
print("*"*25)
print("After assignment marks added to the marks")
df = data.apply(total_marks)
print(df)

   section_A  section_B
0         25         30
1         30         21
2         27         26
3         29         29
4         26         27
*************************
After assignment marks added to the marks
   section_A  section_B
0         35         40
1         40         31
2         37         36
3         39         39
4         36         37

In [136]:
import pandas as pd
data= pd.DataFrame({"Name":["John","Alice","Bob","Jenny"],
                    "Gender":["Male","Female","Male","Female"],
                    "Group":["CSE","MCA","CSE","ECE"],
                    "Age":[21,22,20,25]})
print(data)
print("-"*30)
df1 = pd.Categorical(data["Group"])
print(df1)
df2 = pd.Categorical(data["Gender"])
print(df2)

    Name  Gender Group  Age
0   John    Male   CSE   21
1  Alice  Female   MCA   22
2    Bob    Male   CSE   20
3  Jenny  Female   ECE   25
------------------------------
['CSE', 'MCA', 'CSE', 'ECE']
Categories (3, object): ['CSE', 'ECE', 'MCA']
['Male', 'Female', 'Male', 'Female']
Categories (2, object): ['Female', 'Male']

In [150]:
restaurant = pd.DataFrame({"veg":["veg straters","veg curries","veg biriyani"],
                           "non-veg":["Non-veg straters","curries","biriyani"]
                           })
print(restaurant)
print("\n")
df1 = pd.Categorical(restaurant["veg"])
print(df1)
df2 = pd.Categorical(restaurant["non-veg"])
print(df2)

            veg           non-veg
0  veg straters  Non-veg straters
1   veg curries           curries
2  veg biriyani          biriyani


['veg straters', 'veg curries', 'veg biriyani']
Categories (3, object): ['veg biriyani', 'veg curries', 'veg straters']
['Non-veg straters', 'curries', 'biriyani']
Categories (3, object): ['Non-veg straters', 'biriyani', 'curries']